export const VALIDATE_USER_LOGIN = 'VALIDATE_USER_LOGIN';
export const VALIDATE_USER_LOGIN_SUCCESS = 'VALIDATE_USER_LOGIN_SUCCESS';
export const VALIDATE_USER_LOGIN_FAILURE = 'VALIDATE_USER_LOGIN_FAILURE';
